name: deploy
on: 
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: IDC Publish
      uses: appleboy/ssh-action@v0.1.9
      with: 
        host: 18.191.23.206
        key: ${ { secrets.SSH_KEY }}
        username: ${ { secrets.USER }}     
        run: |
          # sudo apt-get install sshpass
          echo "installed sshpass"
          echo $HOSTNAME
          cd
          cd /home/ubuntu/IDC_FRONTEND
          git pull
          yarn
          yarn build
          cp /build/* /var/www/idc/html/
          sudo systemctl restart nginx
    