name: deploy
on: 
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: IDC Publish
      uses: matheusvanzan/sshpass-action@v2
      with: 
        key: ${ { secrets.SSH_KEY }}
        host: ${ { secrets.HOST }}
        user: ${ { secrets.USER }}     
        run: |
          echo "installed sshpass"
          echo $HOSTNAME
          cd
          cd /home/ubuntu/IDC_FRONTEND
          git pull
          yarn
          yarn build
          cp /build/* /var/www/idc/html/
          sudo systemctl restart nginx
    