name: deploy

on: 
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     env:
        SSH_PRIVATE_KEY: ${ { secrets.SSH_KEY }}
        REMOTE_HOST: ${ { secrets.HOST }}
        REMOTE_USER: ${ { secrets.USER }}
    - name: IDC Publish
      run: |
        echo "installed sshpass"
        cd
        cd IDC_FRONTEND
        git pull
        yarn
        yarn build
        cp /build/* /var/www/idc/html/
        sudo systemctl restart nginx
    